NETWORK_FLOW_INDEX_NAME = "network_flows"
NETWORK_FLOWS_MAPPINGS: dict = {
  "mappings": {
    "properties": {
        "label":{
            "type":"text"
        },
        "src_ip":{
            "type":"text"
        },
        "dst_ip":{
            "type":"text"
        },
        "src_port":{
            "type":"text"
        },
        "dst_port":{
            "type":"text"
        },
        "protocol":{
            "type":"text"
        },
        "timestamp":{
            "type":"text"
        },
        "flow_duration":{
            "type":"text"
        },
        "flow_byts_s":{
            "type":"text"
        },
        "flow_pkts_s":{
            "type":"text"
        },
        "fwd_pkts_s":{
            "type":"text"
        },
        "bwd_pkts_s":{
            "type":"text"
        },
        "tot_fwd_pkts":{
            "type":"text"
        },
        "tot_bwd_pkts":{
            "type":"text"
        },
        "totlen_fwd_pkts":{
            "type":"text"
        },
        "totlen_bwd_pkts":{
            "type":"text"
        },
        "fwd_pkt_len_max":{
            "type":"text"
        },
        "fwd_pkt_len_min":{
            "type":"text"
        },
        "fwd_pkt_len_mean":{
            "type":"text"
        },
        "fwd_pkt_len_std":{
            "type":"text"
        },
        "bwd_pkt_len_max":{
            "type":"text"
        },
        "bwd_pkt_len_min":{
            "type":"text"
        },
        "bwd_pkt_len_mean":{
            "type":"text"
        },
        "bwd_pkt_len_std":{
            "type":"text"
        },
        "pkt_len_max":{
            "type":"text"
        },
        "pkt_len_min":{
            "type":"text"
        },
        "pkt_len_mean":{
            "type":"text"
        },
        "pkt_len_std":{
            "type":"text"
        },
        "pkt_len_var":{
            "type":"text"
        },
        "fwd_header_len":{
            "type":"text"
        },
        "bwd_header_len":{
            "type":"text"
        },
        "fwd_seg_size_min":{
            "type":"text"
        },
        "fwd_act_data_pkts":{
            "type":"text"
        },
        "flow_iat_mean":{
            "type":"text"
        },
        "flow_iat_max":{
            "type":"text"
        },
        "flow_iat_min":{
            "type":"text"
        },
        "flow_iat_std":{
            "type":"text"
        },
        "fwd_iat_tot":{
            "type":"text"
        },
        "fwd_iat_max":{
            "type":"text"
        },
        "fwd_iat_min":{
            "type":"text"
        },
        "fwd_iat_mean":{
            "type":"text"
        },
        "fwd_iat_std":{
            "type":"text"
        },
        "bwd_iat_tot":{
            "type":"text"
        },
        "bwd_iat_max":{
            "type":"text"
        },
        "bwd_iat_min":{
            "type":"text"
        },
        "bwd_iat_mean":{
            "type":"text"
        },
        "bwd_iat_std":{
            "type":"text"
        },
        "fwd_psh_flags":{
            "type":"text"
        },
        "bwd_psh_flags":{
            "type":"text"
        },
        "fwd_urg_flags":{
            "type":"text"
        },
        "bwd_urg_flags":{
            "type":"text"
        },
        "fin_flag_cnt":{
            "type":"text"
        },
        "syn_flag_cnt":{
            "type":"text"
        },
        "rst_flag_cnt":{
            "type":"text"
        },
        "psh_flag_cnt":{
            "type":"text"
        },
        "ack_flag_cnt":{
            "type":"text"
        },
        "urg_flag_cnt":{
            "type":"text"
        },
        "ece_flag_cnt":{
            "type":"text"
        },
        "down_up_ratio":{
            "type":"text"
        },
        "pkt_size_avg":{
            "type":"text"
        },
        "init_fwd_win_byts":{
            "type":"text"
        },
        "init_bwd_win_byts":{
            "type":"text"
        },
        "active_max":{
            "type":"text"
        },
        "active_min":{
            "type":"text"
        },
        "active_mean":{
            "type":"text"
        },
        "active_std":{
            "type":"text"
        },
        "idle_max":{
            "type":"text"
        },
        "idle_min":{
            "type":"text"
        },
        "idle_mean":{
            "type":"text"
        },
        "idle_std":{
            "type":"text"
        },
        "fwd_byts_b_avg":{
            "type":"text"
        },
        "fwd_pkts_b_avg":{
            "type":"text"
        },
        "bwd_byts_b_avg":{
            "type":"text"
        },
        "bwd_pkts_b_avg":{
            "type":"text"
        },
        "fwd_blk_rate_avg":{
            "type":"text"
        },
        "bwd_blk_rate_avg":{
            "type":"text"
        },
        "fwd_seg_size_avg":{
            "type":"text"
        },
        "bwd_seg_size_avg":{
            "type":"text"
        },
        "cwe_flag_count":{
            "type":"text"
        },
        "subflow_fwd_pkts":{
            "type":"text"
        },
        "subflow_bwd_pkts":{
            "type":"text"
        },
        "subflow_fwd_byts":{
            "type":"text"
        },
        "subflow_bwd_byts":{
            "type":"text"
        }
    }
  }
}